development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://grshfbmjyjdwuj:lgiwWDHtVGWqj-4E_r4HiGqnzW@ec2-50-19-236-35.compute-1.amazonaws.com:5432/d6qmqg7d7l4jjq
